<div class="modal" id="punchout-modal">
    <div class="modal-content">
    </div>
</div>

<button class=" button btn-proceed-checkout btn-checkout" id="punchout-button-submit" type="button">
<span>
<span>Transfer Basket Items With Punchout</span>
</span>
</button>

<script type="text/javascript">
    require(["jquery", 'mage/url', 'jquery/ui'], function($,urlBuilder){

        function logOutGoingXMLData(payload)
        {
            $.ajax({
                method: 'POST',
                url: urlBuilder.build('/develodesign_punchout/index/ajaxlogger'),
                data: payload
            }).done(function (response) {
                if(response && response['error'] === false){
                    console.log(response);

                }
            });
        }

        $( "#punchout-button-submit" ).click(function() {
            $('#punchout-modal').show();
            $('#punchout_cxml_form').submit(function () {
                let $xmlStr =  $('#urlencoded_bottom').val();
                /**
                 * Log Outgoing CXML data
                 */
                let payload = {
                    info: $xmlStr,
                    event_type:'Cart Page Punchout',
                    action: 'Develodesign/Punchout/Block/TransferCheckout/Cxml'

                };
                logOutGoingXMLData(payload);
            });
        });
   


    });
</script>
