<?php  /** @var $block \Develodesign\Punchout\Block\Adminhtml\Login */ ?>
<div class="block block-customer-login">
    <input type="text"
           name="punchout-search"
           id="punchout-search"
           class="input-text admin__control-text data-grid-search-control"
           placeholder="<?= /* @noEscape */ __('Search Punchout Groups...') ?>"
           data-mage-init='{"Develodesign_Punchout/js/search":{}}'
           style="margin-bottom: 24px; text-align: center; width:300px"
    />
   <div class="admin__data-grid-wrap" data-role="grid-wrapper">
    <table class="data-grid data-grid-draggable" id="punchout-options" data-role="grid" style="max-width:1500px;">
    <thead>
        <tr>
            <th class="data-grid-th ">Group Name</th>
            <th class="data-grid-th ">CXML Login</th>
            <th class="data-grid-th ">OCI Login</th>
        </tr>
        </thead>
        <?php
        $toggle = "_odd-row";
        foreach ($block->getPunchoutGroups() as $punchoutGroup):
            $toggle = ($toggle=="_odd-row"?"":"_odd-row");
            ?>
            <tr class="<?= /* @noEscape */ $toggle;?> group-row">
                <?php if ($block->hasPunchout($punchoutGroup->getId())):?>
                    <td class="group-name"><?= /* @noEscape */ $punchoutGroup->getGroupName();?></td>
                    <td class="punchout-options cxml-login">
                           <?php if ($cxmlInfo = $block->getCxmlPunchout($punchoutGroup->getId())):
                            if($cxmlInfo['contactEmail']):?>
                                <span class="punchout-option cxml">CXML</span>
                            <?php else:?>
                                    <?= __("No customers set to this group");?>
                            <?php endif;?>
                                <input type="hidden" name="cxml-url"
                                    class="cxml-url"
                                    value="<?= /* @noEscape */ $block->getCXMLSetupUrl() ?>" />
                                <input type="hidden" name="cxml-payload-id"
                                    class="cxml-payload-id"
                                    value="<?= /* @noEscape */ $block->getRandomString() ?>" />
                                <input type="hidden" name="cxml-buyer-cookie"
                                    class="cxml-buyer-cookie"
                                    value="<?= /* @noEscape */ $block->getRandomString(20) ?>" />
                                <input type="hidden" name="cxml-shared-secret"
                                    class="cxml-shared-secret"
                                    value="<?= /* @noEscape */ $cxmlInfo["shared_secret"] ?>" />
                                <input type="hidden" name="cxml-request-operation"
                                    class="cxml-request-operation" value="create" />
                                <input type="hidden" name="cxml-sender-identity"
                                    class="cxml-sender-identity"
                                    value="<?= /* @noEscape */ $cxmlInfo["duns_identity"] ?>" />
                                <input type="hidden" name="cxml-ariba-network-id"
                                    class="cxml-ariba-network-id"
                                    value="<?= /* @noEscape */ $cxmlInfo["ariba_network_id"] ?>" />
                                <input type="hidden" name="cxml-extrinsic-data"
                                    class="cxml-extrinsic-data" value="test" />
                                <input type="hidden" name="cxml-contact-data-name"
                                    class="cxml-contact-data-name"
                                    value="<?= /* @noEscape */ $cxmlInfo["contactName"] ?>" />
                                <input type="hidden" name="cxml-contact-data-email"
                                    class="cxml-contact-data-email"
                                    value="<?= /* @noEscape */ $cxmlInfo["contactEmail"] ?>" />
                                <input type="hidden" name="cxml-return-url"
                                    class="cxml-return-url" value="<?= /* @noEscape */ $block->getBaseUrl() ?>" />
                            <?php endif; ?>
                        </span>
                    </td>
                    <td class="punchout-options oci-login">
                        <?php if ($ociInfo = $block->getOciPunchout($punchoutGroup->getId())): ?>
                                <span class="punchout-option oci">OCI</span>
                                <input type="hidden" name="oci-url"
                                    class="oci-url" value="<?= /* @noEscape */ $block->getOCISetupUrl() ?>" />
                                <input type="hidden" name="oci-hook"
                                    class="oci-hook" value="<?= /* @noEscape */ $block->getBaseUrl() ?>" />
                                <input type="hidden" name="oci-username"
                                    class="oci-username" value="<?= /* @noEscape */ $ociInfo["oci_username"] ?>" />
                                <input type="hidden" name="oci-password"
                                    class="oci-password" value="<?= /* @noEscape */ $ociInfo["oci_password"] ?>" />
                             <?php endif; ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </table>
   </div>
</div>
